from setuptools import setup, find_packages

setup(
    name='brainboost_data_source_requests_package',
    version='0.1.0',
    author='Pablo Tomas Borda',
    author_email='pablotomasborda@hotmail.com',
    description='Sends requests, accepts proxy lists, can use tor proxy',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/brainboost-limited-com/brainboost_data_source_connectors_requests_package',
    package_dir={'brainboost_data_source_requests_package': 'src/brainboost_data_source_requests_package'},
    packages=find_packages(where='src'),
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.10',
    install_requires=[
        'beautifulsoup4==4.12.3',
        'certifi==2024.2.2',
        'charset-normalizer==3.3.2',
        'exceptiongroup==1.2.1',
        'idna==3.7',
        'iniconfig==2.0.0',
        'packaging==24.0',
        'pluggy==1.5.0',
        'PySocks==1.7.1',
        'pytest==8.2.0',
        'pytest-asyncio==0.23.6',
        'requests==2.31.0',
        'soupsieve==2.5',
        'tomli==2.0.1',
        'urllib3==2.2.1',
        'requests[socks]',
        'search_engines @ git+https://github.com/PabloBorda/tools_goldenthinkerextractor.git@7bb819ba7398726876467d64bb777e28b4a9984d#egg=search_engines&subdirectory=Search-Engines-Scraper'
    ]
)
